# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
## relative_permalinks: true

# Setup
title:            Sujeong Cha
tagline:          'Data Scientist'
description:      'M.S. in Data Science Candidate <br> @ <a href="https://cds.nyu.edu/">NYU CDS</a>'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Sujeong Cha'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          08/23/2020

github:
  repo:           https://github.com/sujeongcha
