# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
## relative_permalinks: true

# Setup
title:            Sue Sujeong Cha
tagline:          'Data Scientist'
description:      'M.S. in Data Science Candidate @ <a href="https://cds.nyu.edu/">NYU CDS</a>'
url:              https://sujeongcha.github.io/
baseurl:          /

author:
  name:           'Sujeong Cha'
  url:            

paginate:         3
paginate_path:    "/projects/page:num/"

# Custom vars
version:          08/28/2020

github:
  repo:           https://github.com/sujeongcha
