# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
## relative_permalinks: true

# Setup
title:            SUJEONG &#129505
tagline:          'Data Scientist'
description:      'MS Candidate @ <a href="https://cds.nyu.edu/">NYU CDS</a>'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Sujeong Cha'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sujeongcha
